### PR TITLE
feat(tracking): add google analytics

### PR DESCRIPTION
**Pull request by oceanByte**
We are still testing this feature. Please ignore this until you are added as a reviewer.

### CODE REVIEW

**Comment by oceanByte** [comment]
I think I need your help here @hiba-machfej. We are missing the GOOGLE_ANAYLTICS id. It seems like it is not getting it from the environment variables that you created in render.com. Visit https://near-in-minutes-com-pr-89.onrender.com and check the console logs. It says "Missing the "id" parameter. Add at least one tracking domain ID". 

Do you need to set up the environments for each branch individually?

**Comment by hiba-machfej** [comment]
> I think I need your help here @hiba-machfej. We are missing the GOOGLE_ANAYLTICS id. It seems like it is not getting it from the environment variables that you created in render.com. Visit https://near-in-minutes-com-pr-89.onrender.com and check the console logs. It says "Missing the "id" parameter. Add at least one tracking domain ID".
> 
> Do you need to set up the environments for each branch individually?

yes, it looks like you said. Each branch needs its own environment variable. I added it now let's see.

**Comment by hiba-machfej** [comment]
it is still giving the error after I add it to the branch.

**Comment by hiba-machfej** [comment]
@oceanByte I changed the name from GOOGLE_ANALYTICS to VUE_APP_GOOGLE_ANALYTICS and it's working now.

**Comment by oceanByte** [comment]
This could be merged now once reviewed.

We need to implement a cookie banner as well to be compliant. @hiba-machfej do you want to take care of this in a separate branch? Have a look here: https://www.npmjs.com/package/vue-cookie-law

**Review by hiba-machfej — APPROVED** [review]

**Comment by hiba-machfej** [comment]
> This could be merged now once reviewed.
> 
> We need to implement a cookie banner as well to be compliant. @hiba-machfej do you want to take care of this in a separate branch? Have a look here: https://www.npmjs.com/package/vue-cookie-law

yes sure. thank you for your help with this.

**Comment by hiba-machfej** [comment]
> This could be merged now once reviewed.
> 
> We need to implement a cookie banner as well to be compliant. @hiba-machfej do you want to take care of this in a separate branch? Have a look here: https://www.npmjs.com/package/vue-cookie-law

This library seems to support only vue 2 only.
https://github.com/apertureless/vue-cookie-law/issues/72

I tried to find a vue 3 library but I could not find one. Can you recommend another one?

**Comment by hiba-machfej** [comment]
> > This could be merged now once reviewed.
> > We need to implement a cookie banner as well to be compliant. @hiba-machfej do you want to take care of this in a separate branch? Have a look here: https://www.npmjs.com/package/vue-cookie-law
> 
> This library seems to support only vue 2 only.
> [apertureless/vue-cookie-law#72](https://github.com/apertureless/vue-cookie-law/issues/72)
> 
> I tried to find a vue 3 library but I could not find one. Can you recommend another one? or is it ok if I create a modal with the same text as the library ?

**Comment by oceanByte** [comment]
> I tried to find a vue 3 library but I could not find one. Can you recommend another one? or is it ok if I create a modal with the same text as the library ?

It seems like there are no similar popular libraries for vue3 yet. Have you tried if it works anyway? 
Otherwise, I think you need to create your own banner. This is a little time consuming, but in the end, you can just copy the style and functionality from the suggested library.

If you have the time, you could consider adding vue3 support to the mentioned library. It seems like the community is interested in this as well.  But this might be a more complicated task.

**Comment by hiba-machfej** [comment]
> > I tried to find a vue 3 library but I could not find one. Can you recommend another one? or is it ok if I create a modal with the same text as the library ?
> 
> It seems like there are no similar popular libraries for vue3 yet. Have you tried if it works anyway?
> Otherwise, I think you need to create your own banner. This is a little time consuming, but in the end, you can just copy the style and functionality from the suggested library.
> 
> If you have the time, you could consider adding vue3 support to the mentioned library. It seems like the community is interested in this as well. But this might be a more complicated task.

Yes I tried to use the library and it did not work. I guess I'll have to create the banner for NiM. 

It would be nice to develop vue3 support to the mentioned library but I've never done anything like that, I am not sure how is it done.

**Pull request merged**
