### PR TITLE
Create node.js.yml

### PR DESCRIPTION
**Pull request by hiba-machfej**
This is related to #72. It will create an action and check if the PR follows the style guide. I also added a rule that we can't merge to the `main` branch unless two reviews have accepted the changes.

Screen Shot 2021-07-27 at 1 07 05 PM

### CODE REVIEW

**Comment by hiba-machfej** [comment]
The check will fail I think because `yarn fix` is not yet implemented which is in the previous PR #72

**Comment by humanman** [comment]
> The check will fail I think because `yarn fix` is not yet implemented which is in the previous PR #72

yarn doesn't have a `fix` command, so you'll have to use `npm audit fix`  or install something like `yarn-audit-fix` - https://www.npmjs.com/package/yarn-audit-fix or look for other alternatives https://stackoverflow.com/questions/40057469/what-is-the-difference-between-yarn-lock-and-npms-shrinkwrap

**Comment by hiba-machfej** [comment]
> > The check will fail I think because `yarn fix` is not yet implemented which is in the previous PR #72
> 
> yarn doesn't have a `fix` command, so you'll have to use `npm audit fix` or install something like `yarn-audit-fix` - https://www.npmjs.com/package/yarn-audit-fix or look for other alternatives https://stackoverflow.com/questions/40057469/what-is-the-difference-between-yarn-lock-and-npms-shrinkwrap

That's weird because I tried it locally in the other branch where i added `yarn fix` and it worked. In here it is not available so it won't work. I also tried it in a test repo before I added it to NiM:
https://github.com/hiba-machfej/prettier-guestbook/pull/11

**Comment by humanman** [comment]
> That's weird because I tried it locally in the other branch where i added `yarn fix` and it worked. In here it is not available so it won't work. I also tried it in a test repo before I added it to NiM:
> [hiba-machfej/prettier-guestbook#11](https://github.com/hiba-machfej/prettier-guestbook/pull/11)

That is very weird, because you should have seen `error Command "fix" not found.` in the terminal. You can see from the [yarn docs](https://classic.yarnpkg.com/en/docs/cli/) that `fix` isn't a recognized command. My only guess is that there's a yarn cli package you may have installed globally that _does_ in fact make use of a `yarn fix` command

**Comment by hiba-machfej** [comment]
> > That's weird because I tried it locally in the other branch where i added `yarn fix` and it worked. In here it is not available so it won't work. I also tried it in a test repo before I added it to NiM:
> > [hiba-machfej/prettier-guestbook#11](https://github.com/hiba-machfej/prettier-guestbook/pull/11)
> 
> That is very weird, because you should have seen `error Command "fix" not found.` in the terminal. You can see from the [yarn docs](https://classic.yarnpkg.com/en/docs/cli/) that `fix` isn't a recognized command. My only guess is that there's a yarn cli package you may have installed globally that _does_ in fact make use of a `yarn fix` command

yes in this PR I can see the error you are telling me about as the checks has failed and it's not available in the package.
 
But in this PR https://github.com/near-in-minutes/frontend/pull/72 . If you check the branch `added-rules` locally and run `yarn fix` and it works normally. 
Screen Shot 2021-07-27 at 5 39 00 PM

**Comment by humanman** [comment]
@hiba-machfej  aha! check the `package.json` in the `added-rules` branch - specifically last item in `scripts` section.

**Review by mehtaphysical — APPROVED** [review]

**Review by norrec99 — APPROVED** [review]

**Pull request merged**
